server:
  port: 0
spring:
  kafka:
    bootstrap-servers: http://localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notificationId
      properties:
        json:
          type:
            mapping:
              event:com.fathi.notificationservice.dto.OrderPlaceEvent
  application:
    name: notification-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka